Cabine_homepage:
    path:     /home
    defaults: { _controller: MedicalMedicalBundle:menu/MenuCabine:indexCabine }
    
Cabine_depointment:
    path:     /appointment
    defaults: { _controller: MedicalMedicalBundle:menu/MenuCabine:appointmentCabine }
