<?php

namespace Medical\MedicalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RendezVousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RendezVousRepository extends EntityRepository {
    
     public function findByIdDocteur($id){
        $qb=$this->createQueryBuilder();
        $qb->select('r')
           ->andWhere('r.id_docteur ='.$id)
           ->orderBy('r.heure,r.date_rv','DESC');
        
        return $qb->getQuery()->getResult();
    }
    
}
