<?php

namespace Medical\MedicalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoinRepository extends EntityRepository
{
}
