contact_index:
    path:     /
    defaults: { _controller: "MedicalMedicalBundle:Contact:index" }
    methods:  GET

contact_show:
    path:     /{id}/show
    defaults: { _controller: "MedicalMedicalBundle:Contact:show" }
    methods:  GET

contact_new:
    path:     /new
    defaults: { _controller: "MedicalMedicalBundle:Contact:new" }
    methods:  [GET, POST]

contact_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicalMedicalBundle:Contact:edit" }
    methods:  [GET, POST]

contact_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicalMedicalBundle:Contact:delete" }
    methods:  DELETE
